# Generated by Django 4.0.5 on 2022-06-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='profile_pic',
            field=models.ImageField(upload_to='cppic'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(upload_to='eppic'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='profile_pic',
            field=models.ImageField(upload_to='mppic'),
        ),
    ]
