# Generated by Django 4.0.5 on 2022-06-23 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_client_profile_pic_alter_employee_profile_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='profile_pic',
        ),
    ]
