# Generated by Django 4.0.5 on 2022-06-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_client_profile_pic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=13)),
                ('floor_number', models.IntegerField(default=0)),
                ('business_name', models.CharField(max_length=13)),
                ('contact_person', models.CharField(max_length=13)),
                ('contact_no', models.IntegerField(default=254)),
                ('date_of_site_visit', models.DateField()),
            ],
        ),
    ]
