# Generated by Django 4.0.5 on 2022-06-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_qoute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qoute',
            name='business_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='qoute',
            name='contact_person',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='qoute',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
