# Generated by Django 4.0.5 on 2022-06-23 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_qoute_business_name_alter_qoute_contact_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qoute',
            name='date_of_site_visit',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
